[package]
edition = "2021"
name = "nusamai-gpkg"
version = "0.1.0"

[dependencies]
flatgeom = "0.0.2"
indexmap = "2.13.0"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "sqlite"] }
thiserror = "2.0.18"
url = "2.5.8"

[dev-dependencies]
tokio = { version = "1.49.0", features = ["full"] }
